# Generated by Django 5.0 on 2023-12-23 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=8, unique=True, verbose_name='Number')),
                ('quantity', models.PositiveIntegerField(default=1000000, verbose_name='quantity')),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('COMPLETE', 'COMPLETE')], max_length=16, verbose_name='Status')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.book')),
            ],
        ),
        migrations.CreateModel(
            name='UserCouponList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_used', models.BooleanField(default=False, verbose_name='Is used?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
